### ISSUE TITLE
openjdk10 become 'undefined'

### ISSUE THREAD

**Issue by Sicaine** [AdoptOpenJDK/openjdk10-releases#2]
The release for openjdk10 became undefined. 7 Days ago the bot apperently broke?

I'm unable to use brew with it right now.

**Comment by sxa** [comment]
Almost certainly as a result of https://github.com/AdoptOpenJDK/openjdk-build/issues/317 - we are working to get release builds back, starting with openjdk8, then openjdk10 ...

**Comment by karianna** [comment]
I think this is resolved now.
