### ISSUE TITLE
The target file does not exist

### ISSUE THREAD

**Issue by xunfeng1980** [AdoptOpenJDK/openjdk10-releases#3]
~  brew install adoptopenjdk-openjdk10                                                                                                                                    
==> Installing adoptopenjdk-openjdk10 from adoptopenjdk/openjdk
==> Downloading https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/201807101745/OpenJDK10_x64_Mac_201807101745.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "adoptopenjdk-openjdk10"
Download failed: https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/201807101745/OpenJDK10_x64_Mac_201807101745.tar.gz

**Comment by luxcn** [comment]
It is : https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.1%2B10/OpenJDK10_x64_Mac_201807101745.tar.gz

**Comment by xunfeng1980** [comment]
https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.1%2B10/OpenJDK10_x64_Mac_201807101745.tar.gz
